name: amstero-workspace

volumes:
  amstero-credentials:

services:
  amstero-toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: amstero-toolbox:latest
    container_name: amstero-toolbox
    volumes:
      - ../../:/workspace
      - amstero-credentials:/workspace/runtime/credentials
    stdin_open: true
    tty: true
    working_dir: /workspace