name: amstero-workspace

services:
  amstero-toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: amstero-toolbox:latest
    container_name: amstero-toolbox
    volumes:
      - ../../:/workspace
    stdin_open: true
    tty: true
    working_dir: /workspace